-- Stage 2 reference schema. Alembic revision 0002_stage2_telegram is executable truth.
-- UUID values are generated by the application; timestamps are UTC timestamptz.

CREATE TABLE drafts (
  id uuid PRIMARY KEY,
  title varchar(300),
  current_revision_id uuid,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  archived_at timestamptz
);

CREATE TABLE post_revisions (
  id uuid PRIMARY KEY,
  draft_id uuid NOT NULL REFERENCES drafts(id),
  revision_number integer NOT NULL CHECK (revision_number > 0),
  text text NOT NULL,
  text_sha256 varchar(64) NOT NULL CHECK (length(text_sha256) = 64),
  canonicalization_version varchar(32) NOT NULL,
  supersedes_revision_id uuid REFERENCES post_revisions(id),
  created_by varchar(200) NOT NULL,
  created_at timestamptz NOT NULL,
  UNIQUE (draft_id, revision_number)
);
ALTER TABLE drafts ADD CONSTRAINT fk_drafts_current_revision
  FOREIGN KEY (current_revision_id) REFERENCES post_revisions(id);
CREATE INDEX ix_drafts_current_revision_id ON drafts(current_revision_id);
CREATE INDEX ix_post_revisions_draft_id ON post_revisions(draft_id);

CREATE TABLE approvals (
  id uuid PRIMARY KEY,
  revision_id uuid NOT NULL REFERENCES post_revisions(id),
  revision_sha256 varchar(64) NOT NULL CHECK (length(revision_sha256) = 64),
  approval_fingerprint varchar(64) NOT NULL UNIQUE
    CHECK (length(approval_fingerprint) = 64),
  approved_by varchar(200) NOT NULL,
  approved_at timestamptz NOT NULL,
  revoked_at timestamptz,
  revocation_reason varchar(500),
  idempotency_key varchar(128) NOT NULL UNIQUE,
  created_at timestamptz NOT NULL
);
CREATE INDEX ix_approvals_revision_id ON approvals(revision_id);

CREATE TABLE linkedin_connections (
  id uuid PRIMARY KEY,
  owner_subject varchar(200) NOT NULL UNIQUE,
  encrypted_access_token text NOT NULL,
  token_expires_at timestamptz NOT NULL,
  scopes jsonb NOT NULL,
  person_urn varchar(300) NOT NULL,
  token_metadata jsonb NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  last_validated_at timestamptz,
  disabled_at timestamptz
);

CREATE TABLE publications (
  id uuid PRIMARY KEY,
  draft_id uuid NOT NULL REFERENCES drafts(id),
  revision_id uuid NOT NULL REFERENCES post_revisions(id),
  approval_id uuid NOT NULL REFERENCES approvals(id),
  connection_id uuid NOT NULL REFERENCES linkedin_connections(id),
  status varchar(32) NOT NULL
    CHECK (status IN ('PREPARED','PUBLISHING','PUBLISHED','FAILED','PUBLISH_UNCERTAIN')),
  request_fingerprint varchar(64) NOT NULL CHECK (length(request_fingerprint) = 64),
  idempotency_key varchar(128) NOT NULL UNIQUE,
  linkedin_post_identifier varchar(500),
  prepared_at timestamptz NOT NULL,
  started_at timestamptz,
  completed_at timestamptz,
  failure_category varchar(100),
  safe_error_code varchar(100),
  safe_error_message varchar(300),
  request_attempted boolean NOT NULL,
  response_received boolean NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  UNIQUE (revision_id, connection_id),
  CHECK (status <> 'PUBLISHED' OR linkedin_post_identifier IS NOT NULL)
);
CREATE INDEX ix_publications_status ON publications(status);
CREATE INDEX ix_publications_started_at ON publications(started_at);
CREATE INDEX ix_publications_stale ON publications(status, started_at)
  WHERE status = 'PUBLISHING';

CREATE TABLE publication_attempts (
  id uuid PRIMARY KEY,
  publication_id uuid NOT NULL REFERENCES publications(id) UNIQUE,
  attempt_number integer NOT NULL CHECK (attempt_number = 1),
  stage varchar(50) NOT NULL,
  started_at timestamptz NOT NULL,
  completed_at timestamptz,
  request_attempted boolean NOT NULL,
  response_received boolean NOT NULL,
  http_status integer,
  outcome varchar(32) NOT NULL
    CHECK (outcome IN ('STARTED','PUBLISHED','FAILED','PUBLISH_UNCERTAIN')),
  safe_error_category varchar(100),
  safe_error_code varchar(100),
  safe_error_message varchar(300),
  linkedin_post_identifier varchar(500)
);

CREATE TABLE audit_events (
  id uuid PRIMARY KEY,
  aggregate_type varchar(50) NOT NULL,
  aggregate_id uuid NOT NULL,
  event_type varchar(100) NOT NULL,
  actor_type varchar(50) NOT NULL,
  actor_id varchar(200) NOT NULL,
  request_id varchar(100) NOT NULL,
  occurred_at timestamptz NOT NULL,
  safe_metadata jsonb NOT NULL
);
CREATE INDEX ix_audit_aggregate
  ON audit_events(aggregate_type, aggregate_id, occurred_at);

CREATE TABLE idempotency_records (
  id uuid PRIMARY KEY,
  scope varchar(250) NOT NULL,
  idempotency_key varchar(128) NOT NULL,
  request_fingerprint varchar(64) NOT NULL CHECK (length(request_fingerprint) = 64),
  resource_type varchar(50) NOT NULL,
  resource_id uuid NOT NULL,
  created_at timestamptz NOT NULL,
  UNIQUE (scope, idempotency_key)
);

CREATE TABLE external_approval_requests (
  id uuid PRIMARY KEY,
  draft_id uuid NOT NULL REFERENCES drafts(id),
  revision_id uuid NOT NULL REFERENCES post_revisions(id),
  revision_sha256 varchar(64) NOT NULL CHECK (length(revision_sha256) = 64),
  approval_fingerprint varchar(64) NOT NULL
    CHECK (length(approval_fingerprint) = 64),
  channel varchar(32) NOT NULL,
  status varchar(32) NOT NULL
    CHECK (status IN ('PENDING','APPROVED','REJECTED','EXPIRED','INVALIDATED','CONSUMED')),
  callback_token_hash varchar(64) NOT NULL UNIQUE
    CHECK (length(callback_token_hash) = 64),
  telegram_owner_user_id bigint NOT NULL,
  telegram_chat_id bigint NOT NULL,
  requested_by varchar(200) NOT NULL,
  requested_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  decided_at timestamptz,
  decision_actor_id varchar(200),
  decision varchar(32)
    CHECK (decision IS NULL OR decision IN ('APPROVE_AND_PUBLISH','REJECT')),
  consumed_at timestamptz,
  invalidated_at timestamptz,
  invalidation_reason varchar(300),
  message_external_id varchar(200),
  approval_id uuid REFERENCES approvals(id),
  publication_id uuid REFERENCES publications(id),
  idempotency_key varchar(128) NOT NULL UNIQUE,
  decision_idempotency_key varchar(128) UNIQUE,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);
CREATE INDEX ix_external_approval_requests_revision_id
  ON external_approval_requests(revision_id);
CREATE INDEX ix_external_approval_status_expiry
  ON external_approval_requests(status, expires_at);
CREATE INDEX ix_external_approval_telegram_owner_chat
  ON external_approval_requests(telegram_owner_user_id, telegram_chat_id);
CREATE UNIQUE INDEX uq_external_approval_pending_revision_channel
  ON external_approval_requests(revision_id, channel)
  WHERE status = 'PENDING';

CREATE TABLE telegram_deliveries (
  id uuid PRIMARY KEY,
  approval_request_id uuid NOT NULL REFERENCES external_approval_requests(id),
  phase varchar(20) NOT NULL,
  delivery_status varchar(20) NOT NULL
    CHECK (delivery_status IN ('SENT','FAILED')),
  message_external_id varchar(200),
  sent_at timestamptz,
  edited_at timestamptz,
  safe_error_category varchar(100),
  attempts integer NOT NULL CHECK (attempts = 1),
  idempotency_key varchar(128) NOT NULL UNIQUE,
  created_at timestamptz NOT NULL,
  UNIQUE (approval_request_id, phase)
);

-- The migration installs BEFORE UPDATE OR DELETE triggers on post_revisions and
-- audit_events through prevent_stage1_mutation(), enforcing immutable revisions
-- and an append-only audit trail.
